import { GradientProps } from "@/types"
import { generateUid } from "@/lib"

export const example_gradients: GradientProps[] = [
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#00FFFF", "#008080"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#FF7F50", "#87CEFA"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#9370DB", "#FFB6C1"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#FF00FF", "#00FFFF"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#FFD700", "#008080"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#FFA500", "#00CED1"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#800080", "#FFA07A"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#FFC0CB", "#FF69B4"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
	{
		created: new Date("2024-08-08").toISOString(),
		id: generateUid("gradient"),
		colors: ["#4682B4", "#B0C4DE"],
		positions: [0, 100],
		rotation: 90,
		type: "linear",
		name: "Example Gradient",
	},
]
